version: '3.0'

services:
    backend:
        build: .
        command: node app.js
        volumes:
            - ./:/app
            - node_modules:/app/node_modules
        ports:
            - 3000:3000
volumes:
    node_modules: